version: '3.8'

services:
  app:
    image: ahmedbenhmida/laravel-app:latest
    restart: always
    working_dir: /var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - storage:/var/www/storage
    command: >
      sh -c "php artisan migrate --force && 
             php artisan config:cache && 
             php artisan route:cache && 
             php artisan view:cache && 
             php-fpm"
    networks:
      - laravel_network

  webserver:
    image: ahmedbenhmida/laravel-nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - storage:/var/www/storage
    depends_on:
      - app
    networks:
      - laravel_network

volumes:
  storage:
    driver: local

networks:
  laravel_network:
    driver: bridge